import type { Itinerary } from '@/types'

export function exportGPX(itinerary: Itinerary): void {
  const waypoints = itinerary.days.flatMap((d) => d.waypoints)

  const wptXml = waypoints
    .map(
      (w) =>
        `  <wpt lat="${w.coord.lat}" lon="${w.coord.lng}">
    <name>${escapeXml(w.label)}</name>
    ${w.note ? `<desc>${escapeXml(w.note)}</desc>` : ''}
  </wpt>`
    )
    .join('\n')

  const trkptXml = itinerary.route.waypoints
    .map((w) => `      <trkpt lat="${w.coord.lat}" lon="${w.coord.lng}"><name>${escapeXml(w.label)}</name></trkpt>`)
    .join('\n')

  const gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="RouteAU" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${escapeXml(itinerary.name)}</name>
    <desc>Generated by RouteAU — Australia's Road Trip Planner</desc>
    <time>${new Date().toISOString()}</time>
  </metadata>
${wptXml}
  <trk>
    <name>${escapeXml(itinerary.name)}</name>
    <trkseg>
${trkptXml}
    </trkseg>
  </trk>
</gpx>`

  const blob = new Blob([gpx], { type: 'application/gpx+xml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${itinerary.name.replace(/\s+/g, '-')}.gpx`
  a.click()
  URL.revokeObjectURL(url)
}

function escapeXml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
